### ISSUE TITLE
deduplicate command sequences

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/GreedyBear#535]
from the internal logs, it seems that same command sequences are stored multiple times. to investigate

**Comment by regulartim** [comment]
Would you attach or  send me the logs?

**Comment by mlodic** [comment]
sorry for the late answer, I am AFK these days, I'll get back as soon as I can on this

**Comment by mlodic** [comment]
Tim, when I checked that I noticed that there were some identical commands here: 

<img width="590" height="175" alt="Image" src="https://github.com/user-attachments/assets/18a7a1a9-ae29-4469-a259-9215032492a3" />

They are dated March so I am not sure whether this was fixed. In any case, I did a little change here [fb9aeeadba9987dcec9b3839fa79ea7f23d7743c](https://github.com/intelowlproject/GreedyBear/pull/540) and I'll test out whether this does not happen anymore.

I also added some logs because I noticed that there were no any recent commands sequences collected in the last months so it has been weird to me.

**Comment by regulartim** [comment]
> They are dated March so I am not sure whether this was fixed. 

No, I do not think it is fixed.

The model definition of the command sequences does not allow duplicates, because the `commands_hash` has a unique constraint:

``` python
class CommandSequence(models.Model):
    first_seen = models.DateTimeField(blank=False, default=datetime.now)
    last_seen = models.DateTimeField(blank=False, default=datetime.now)
    commands = pg_fields.ArrayField(models.CharField(max_length=1024, blank=True), blank=False, null=False, default=list)
    commands_hash = models.CharField(max_length=64, unique=True, blank=True, null=True)
    cluster = models.IntegerField(blank=True, null=True)
```

It would be interesting to see the content of the `commands_hash` field for two of the duplicate sequences. Would you provide this information?

**Comment by mlodic** [comment]
it is empty. My speculation is that the deduplication does not happen sometimes because we dont always have the closing event from cowrie and the code did the deduplication there. I have just deployed a little change about that and I'll monitor it in the next days and update here

**Comment by regulartim** [comment]
> My speculation is that the deduplication does not happen sometimes because we dont always have the closing event from cowrie and the code did the deduplication there.

Yes, that sounds plausible. Then the question is why do we miss the closing event? That shouldn't happen. You can check if a closing event was recorded for a particular session, if the session has a `duration` property. On my private instance I do not see any session without a closing event.

**Comment by mlodic** [comment]
I guess you are right, I wanted to experiment with the honeynet servers which seem to be sometimes faulty. I still can't have access to Kibana but this problem needs to be definitevely solved otherwise I can't debug further

**Comment by regulartim** [comment]
Maybe we could add a cleanup routine that deletes command sequences that are older than 1 day but do not have a `commands_hash` value (which means that they do not have the closing event from cowrie).

**Comment by mlodic** [comment]
theoretically with the change implemented [here](https://github.com/intelowlproject/GreedyBear/pull/540/files), that should not happen.

**Comment by rahulgunwanistudy-2005** [comment]
Hi, I've opened a PR to fix this issue: #878
The bug was in _get_sessions() where save_command_sequence() was being called unconditionally, even when _deduplicate_command_sequence() had already found an existing record. The fix captures the return value and only saves when the sequence is new.

**Comment by rahulgunwanistudy-2005** [comment]
I should have asked to be assigned first before submitting the PR, sorry for skipping that step. I've opened PR #878 with the fix. Happy to make any changes if needed, or close the PR if you'd prefer to assign it to someone else first.

**Comment by regulartim** [comment]
> The bug was in _get_sessions() where save_command_sequence() was being called unconditionally, even when _deduplicate_command_sequence() had already found an existing record. 

Hey @rahulgunwanistudy-2005 ! I disagree, this is not the bug. 

This is how `_deduplicate_command_sequence` works:

When there is a duplicate:
- Looks up existing CommandSequence by hash and finds it
- Replaces session.commands with the existing DB object (cmd_seq) 
- Updates last_seen on that existing object 

When there is no duplicate:
- Lookup returns None
- Sets the hash on the new, unsaved CommandSequence

In both cases, save_command_sequence should be called — it either creates a new record or updates last_seen on an existing one. The return value of _deduplicate_command_sequence is intentionally unused because the subsequent .save() is correct for both paths.

@mlodic Did you encounter the issue again? I did not.

**Comment by rahulgunwanistudy-2005** [comment]
Hi @regulartim, thank you for the detailed explanation,  you're absolutely right, and I apologise for the mistake.

I misread _deduplicate_command_sequence and assumed it was skipping the save when a duplicate was found, but I now understand that save_command_sequence is intentionally called in both cases. I'll close this PR.

I also notice our fix introduced a new bug, is_duplicate is referenced outside the if session_record.commands is not None block, which could cause a NameError. 

Sorry for the noise.

**Comment by regulartim** [comment]
No worries @rahulgunwanistudy-2005 ! :)

**Comment by xovishnukosuri** [comment]
Hi, I'd like to work on this issue. Based on the discussion, the root cause is that `CommandSequence` records with a null `commands_hash` bypass the unique constraint (PostgreSQL allows multiple NULLs in unique columns), leading to duplicates.

I plan to address this with two changes:
1. **Cleanup routine**: Add a `delete_orphaned_command_sequences` method to remove `CommandSequence` records with null `commands_hash` older than 1 day (as @regulartim suggested), integrated into the existing `CleanUp` cronjob.
2. **Race condition handling**: Wrap the command sequence save in `transaction.atomic()` and catch `IntegrityError` to handle the case where two concurrent extraction workers try to create the same hash simultaneously - falling back to fetching the existing record.

Will open a PR shortly.

**Comment by Atul-Chahar** [comment]
Hi @regulartim, I'd like to work on this. Based on your earlier suggestion, I'm thinking of adding a cleanup step in the existing `CleanUp` cronjob to delete command sequences without a `commands_hash` that are older than one day. Can you assign me?

**Comment by aditisingh70330** [comment]
@regulartim can you assign me this issue?

**Comment by regulartim** [comment]
I think this has been fixed in #540 . Will close it for now.
